FROM python:3.14-alpine

WORKDIR /app

COPY . .

RUN apk add --no-cache \
    mariadb-connector-c-dev \
    gcc \
    musl-dev

RUN pip install -r requirements.prod.txt

EXPOSE 8000

WORKDIR /app/app_logs

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0", "run:app"]